/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package udp;

import java.awt.event.KeyEvent;
import javax.swing.JScrollPane;
import javax.swing.text.DefaultCaret;

/**
 *
 * @author prodrigo
 */
public class FormServidor extends javax.swing.JFrame {

    private Servidor srv;
    
    public FormServidor() {
        initComponents();
    }
    
    public FormServidor(String PORTA_ENVIAR, String PORTA_RECEBER){
        this();
        txtPortaEnviar.setText(PORTA_ENVIAR);
        txtPortaReceber.setText(PORTA_RECEBER);
        
        srv = new Servidor(
            txtHistorico,txtURL.getText(),
            txtPortaEnviar.getText(),
            txtPortaReceber.getText()
        );
        srv.start();        
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblMensagem = new javax.swing.JLabel();
        txtMensagem = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtHistorico = new javax.swing.JTextArea();
        txtURL = new javax.swing.JTextField();
        lblMensagem1 = new javax.swing.JLabel();
        txtPortaReceber = new javax.swing.JTextField();
        lblMensagem2 = new javax.swing.JLabel();
        txtPortaEnviar = new javax.swing.JTextField();
        lblMensagem3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblMensagem.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblMensagem.setText("Mensagem");

        txtMensagem.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        txtMensagem.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtMensagemKeyReleased(evt);
            }
        });

        txtHistorico.setColumns(20);
        txtHistorico.setFont(new java.awt.Font("Monospaced", 0, 14)); // NOI18N
        txtHistorico.setRows(5);
        jScrollPane1.setViewportView(txtHistorico);

        txtURL.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        txtURL.setText("127.0.01");
        txtURL.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtURLKeyReleased(evt);
            }
        });

        lblMensagem1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblMensagem1.setText("URL");

        txtPortaReceber.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        txtPortaReceber.setText("5001");
        txtPortaReceber.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPortaReceberKeyReleased(evt);
            }
        });

        lblMensagem2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblMensagem2.setText("Receber");

        txtPortaEnviar.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        txtPortaEnviar.setText("5000");
        txtPortaEnviar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPortaEnviarKeyReleased(evt);
            }
        });

        lblMensagem3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblMensagem3.setText("Enviar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblMensagem1)
                            .addComponent(txtURL, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblMensagem3)
                            .addComponent(txtPortaEnviar, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblMensagem2)
                            .addComponent(txtPortaReceber, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jScrollPane1)
                        .addComponent(txtMensagem, javax.swing.GroupLayout.PREFERRED_SIZE, 439, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblMensagem)))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblMensagem1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtURL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblMensagem2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtPortaReceber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblMensagem3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtPortaEnviar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(lblMensagem)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtMensagem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtMensagemKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMensagemKeyReleased
        
        if (evt.getKeyCode() == KeyEvent.VK_ENTER){
            srv.enviar(txtMensagem.getText());
            txtMensagem.setText("");
            txtMensagem.requestFocus();
        }
        
    }//GEN-LAST:event_txtMensagemKeyReleased

    private void txtURLKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtURLKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtURLKeyReleased

    private void txtPortaReceberKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPortaReceberKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPortaReceberKeyReleased

    private void txtPortaEnviarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPortaEnviarKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPortaEnviarKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormServidor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormServidor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormServidor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormServidor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormServidor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblMensagem;
    private javax.swing.JLabel lblMensagem1;
    private javax.swing.JLabel lblMensagem2;
    private javax.swing.JLabel lblMensagem3;
    private javax.swing.JTextArea txtHistorico;
    private javax.swing.JTextField txtMensagem;
    private javax.swing.JTextField txtPortaEnviar;
    private javax.swing.JTextField txtPortaReceber;
    private javax.swing.JTextField txtURL;
    // End of variables declaration//GEN-END:variables
}
